---
driver:
  name: docker

platforms:
  - name: ${MOLECULE_DISTRO:-debian13}
    image: geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible:latest

provisioner:
  name: ansible
  config_options:
    defaults:
      callback_result_format: yaml
      verbosity: 0
