---
driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: debian11
    box: debian/bullseye64
    config_options:
      vm.boot_timeout: 600
    memory: 1024

provisioner:
  name: ansible
  config_options:
    defaults:
      callback_result_format: yaml
      verbosity: 0
