---
services:
  docker_app:
    image: ghcr.io/deadnews/deadnews-template-go:2.0.6@sha256:981178cb36eababcbaf8209d5ff19c9cb01c107ec478dd3128ab597c8e12be94
    container_name: docker-app
    restart: on-failure:2
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:${SERVICE_PORT}/health || exit 1
      interval: 60s
      retries: 3
      timeout: 10s
      start_period: 60s
    ports:
      - 127.0.0.1:${SERVICE_PORT}:${SERVICE_PORT}
    environment:
      SERVICE_PORT: ${SERVICE_PORT}
