---
# Deploy Docker Compose projects

- name: Check if docker_compose_files is defined when docker_compose_state is present
  ansible.builtin.fail:
    msg: The parameter 'docker_compose_files' is required when 'docker_compose_state' is 'present'
  when:
    - docker_compose_state == 'present'
    - docker_compose_files is not defined

- name: Deploy Docker Compose project
  when: docker_compose_state == 'present'
  ansible.builtin.include_role:
    name: deadnews.util.docker_compose
    tasks_from: deploy

- name: Remove Docker Compose project
  when: docker_compose_state == 'absent'
  ansible.builtin.include_role:
    name: deadnews.util.docker_compose
    tasks_from: remove
