---
# Schedule Docker images cleanup

- name: Set the cron job user
  ansible.builtin.set_fact:
    docker_user: "{{ docker_rootless_user if docker_rootless else 'root' }}"

- name: Create a cron for clear dangling Docker images
  ansible.builtin.cron:
    name: clear dangling Docker images
    special_time: weekly
    user: "{{ docker_user }}"
    job: docker image prune -f
    cron_file: docker-image-clear-dangling-{{ docker_user }}

- name: Create a cron for clear unused Docker images created more than specified time ago
  ansible.builtin.cron:
    name: clear unused Docker images created more than {{ docker_cleanup_scheduled_until | default('672h') }} ago
    special_time: weekly
    user: "{{ docker_user }}"
    job: docker image prune -f --all --filter "until={{ docker_cleanup_scheduled_until | default('672h') }}"
    cron_file: docker-image-clear-unused-{{ docker_user }}
